### ISSUE TITLE
How can I run this code on mutli GPU?

### ISSUE THREAD

**Issue by ZhenYangIACAS** [facebookresearch/UnsupervisedMT#1]
Hi, since I am not so familier with pytorch, I want to know how can I run this code on multi-GPU framework?

**Comment by glample** [comment]
Hi,

Multi-GPU is not supported yet. We may add it in the future, but the gain in speed would not be huge, as the online back-translation generation process takes a significant part of training time. We tried to do online back-translation on GPUs, but this did not help a lot..

That being said, the code is usually pretty fast to converge (a few days on single GPU), as opposed to standard supervised systems.
