### ISSUE TITLE
Interpret the result of PBSMT

### ISSUE THREAD

**Issue by shawnzaru** [facebookresearch/UnsupervisedMT#11]
Could somebody explain to me what each of the numbers below means?

BLEU = 13.49, 51.9/21.1/10.2/5.2 (BP=0.869, ratio=0.877, hyp_len=71143, ref_len=81098)
End of training. Experiment is stored in: ./UnsupervisedMT/PBSMT/moses_train_en-fr

Thanks

**Comment by glample** [comment]
This is the output of this script: https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl

13.49 is the BLEU score (the value you care about), "51.9/21.1/10.2/5.2" are the precisions of 1-
grams, 2-grams, 3-grams and 4-grams respectively.

hyp_len is the number of words in your hypothesis (model generations), ref_len is the number of words in your references, ratio is the ratio between these 2 numbers, and BP is the brevity penalty.
