### ISSUE TITLE
cannot reproduce the results of unsupervised NMT

### ISSUE THREAD

**Issue by tobyyouup** [facebookresearch/UnsupervisedMT#12]
I use the command `python main.py --exp_name test --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb True --share_output_emb True --langs 'en,fr' --n_mono -1 --mono_dataset 'en:./data/mono/all.en.tok.60000.pth,,;fr:./data/mono/all.fr.tok.60000.pth,,' --para_dataset 'en-fr:,./data/para/dev/newstest2013-ref.XX.60000.pth,./data/para/dev/newstest2014-fren-src.XX.60000.pth' --mono_directions 'en,fr' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'fr-en-fr,en-fr-en' --pretrained_emb './data/mono/all.en-fr.60000.vec' --pretrained_out True --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 --otf_num_processes 30 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 500000 --stopping_criterion bleu_en_fr_valid,10`

to run the codes, but finally I can just get BLEU score:
bleu_en_fr_test -> 18.400000
bleu_fr_en_test -> 18.610000

I cannot get the score above 23.0 BLEU. This the final log:
`INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - BLEU ./dumped/test/2w3b5142k5/hyp107.en-fr-en.test.txt ./dumped/test/2w3b5142k5/ref.fr-en.test.txt : 45.160000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - epoch -> 107.000000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - ppl_en_fr_valid -> 65.701571
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - bleu_en_fr_valid -> 15.980000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - ppl_fr_en_valid -> 91.976447
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - bleu_fr_en_valid -> 15.940000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - ppl_en_fr_test -> 41.084037
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - bleu_en_fr_test -> 18.400000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - ppl_fr_en_test -> 59.131132
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - bleu_fr_en_test -> 18.610000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - ppl_fr_en_fr_valid -> 3.330721
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - bleu_fr_en_fr_valid -> 44.190000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - ppl_fr_en_fr_test -> 2.995039
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - bleu_fr_en_fr_test -> 44.170000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - ppl_en_fr_en_valid -> 3.518063
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - bleu_en_fr_en_valid -> 45.580000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - ppl_en_fr_en_test -> 3.443367
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - bleu_en_fr_en_test -> 45.160000
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - __log__:{"epoch": 107, "ppl_en_fr_valid": 65.70157069383522, "bleu_en_fr_valid": 15.98, "ppl_fr_en_valid": 91.9764473614227, "bleu_fr_en_valid": 15.94, "ppl_en_fr_test": 41.084036855000534, "bleu_en_fr_test": 18.4, "ppl_fr_en_test": 59.131132225283814, "bleu_fr_en_test": 18.61, "ppl_fr_en_fr_valid": 3.3307206599236614, "bleu_fr_en_fr_valid": 44.19, "ppl_fr_en_fr_test": 2.9950391883629113, "bleu_fr_en_fr_test": 44.17, "ppl_en_fr_en_valid": 3.518062580498395, "bleu_en_fr_en_valid": 45.58, "ppl_en_fr_en_test": 3.4433665669537183, "bleu_en_fr_en_test": 45.16}
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - Not a better validation score (10 / 10).
INFO - 09/04/18 17:44:09 - 1 day, 21:24:48 - Stopping criterion has been below its best value more than 10 epochs. Ending the experiment...`

I follow the README step by step. So is there anything that I miss?

**Comment by glample** [comment]
Hi, can you send me your full training log?

**Comment by tobyyouup** [comment]
Thanks for your reply, I put the log in the gist: https://gist.github.com/tobyyouup/1b093ddec2155a053df3171df463bf35

Look forward to your further reply :)

**Comment by tobyyouup** [comment]
oops, I just use one layer encoder and decoder in the shell scripts. No wonder cannot get the high BLEU score. I will fix and run again. Will report to you if I reproduce the score. Thanks!

**Comment by tobyyouup** [comment]
@glample   I have already reproduced the BLEU score of en-fr, nearly 25 BLEU score, thanks for your help!

**Comment by glample** [comment]
Thank you for confirming. I just reran the command above, and after 4 days I get:

```
Epoch - 127

PPL  - en -> fr (valid)       -  35.51
PPL  - fr -> en (valid)       -  46.04
BLEU - en -> fr (valid)       -  22.41
BLEU - fr -> en (valid)       -  20.92

PPL  - en -> fr (test)        -  19.46
PPL  - fr -> en (test)        -  25.52
BLEU - en -> fr (test)        -  25.99
BLEU - fr -> en (test)        -  25.10

PPL - en -> fr -> en (valid)  -   1.79
PPL - fr -> en -> fr (valid)  -   1.90
PPL - en -> fr -> en (test)   -   1.81
PPL - fr -> en -> fr (test)   -   1.75

BLEU - en -> fr -> en (valid) -  62.95
BLEU - fr -> en -> fr (valid) -  60.39
BLEU - en -> fr -> en (test)  -  62.08
BLEU - fr -> en -> fr (test)  -  61.50
```

**Comment by glample** [comment]
@chang-xu were you able to reproduce the en-fr results? Or you only tried en-de?

**Comment by chang-xu** [comment]
@glample I tried to reproduce the en-fr results:

below is my reproduced results in en-fr after **83** epochs:

> ppl_en_fr_valid -> 36.674233
> bleu_en_fr_valid -> 20.800000
> ppl_fr_en_valid -> 49.298057
> bleu_fr_en_valid -> 20.070000
> ppl_en_fr_test -> 20.068776
> bleu_en_fr_test -> **24.230000**
> ppl_fr_en_test -> 27.563477
> bleu_fr_en_test -> **23.720000**
> ppl_fr_en_fr_valid -> 1.966098
> bleu_fr_en_fr_valid -> 58.630000
> ppl_fr_en_fr_test -> 1.806122
> bleu_fr_en_fr_test -> 59.120000
> ppl_en_fr_en_valid -> 1.889292
> bleu_en_fr_en_valid -> 61.100000
> ppl_en_fr_en_test -> 1.892268
> bleu_en_fr_en_test -> 60.780000
