### ISSUE TITLE
CUDA Out of Memory

### ISSUE THREAD

**Issue by ptamas88** [facebookresearch/UnsupervisedMT#13]
Hi!
Is it normal that I am out of gpu memory when training the en-fr dataset on a GTX 1080Ti? (11 GB VRAM)
The training failed after 1000 step with the following message:
```
INFO - 09/08/18 11:28:33 - 0:29:30 -    1000 -   72.85 sent/s -  2105.00 words/s - XE-en-en:  3.7582 || XE-fr-fr:  3.5753 || XE-fr-en-fr:  5.0131 || XE-en-fr-en:  5.4994 || ENC-L2-en:  5.1436 || ENC-L2-fr:  5.1294 - LR dec=1.0000e-04,enc=1.0000e-04 - Sentences generation time:  56.93s (64.80%)
Traceback (most recent call last):
  File "main.py", line 328, in <module>
    trainer.otf_bt(batch, params.lambda_xe_otfd, params.otf_backprop_temperature)
  File "/data/UnsupervisedMT/NMT/src/trainer.py", line 706, in otf_bt
    loss.backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory
```
Should I decrease the layer number of the transformer model or the size of the dataset?

Thanks

**Comment by glample** [comment]
Hi,

What configuration are you using? What is your training command?
11GB should be fine, but I have never tried on 1080Ti so I'm not sure. To reduce the memory usage you can either:
- share more layers (sharing everything is usually fine)
- use less layers
- set a smaller maximum sentence length during training, i.e. `--max_len 100` for instance (this is probably the best solution with sharing more layers)

**Comment by glample** [comment]
I'm not sure, I never tried with 3 layers. 4 and 5 gave roughly the same results though. Another solution is to use 40k BPE instead of 60k, but 60k was usually giving slightly better results.

**Comment by glample** [comment]
Actually there are other things you can share that will significantly reduce the memory usage:
**share_encdec_emb** to share the encoder and decoder input embeddings
**share_decpro_emb** to share the decoder input and output embeddings
**share_output_emb** to share the source and target output embeddings in the decoder
All these parameters are by default set to False, and on the language pairs I tried setting any of them to True didn't give very different results.

**Comment by ptamas88** [comment]
I successfully ran the script for 27 epochs with the above booleans set to True mentioned by @glample , and set --n_enc_layers 3 --n_dec_layers 3 --share_enc 2 --share_dec 2, and also --max_len=100.
Thanks for the help.
