### ISSUE TITLE
RuntimeError: cuda runtime error (2) 

### ISSUE THREAD

**Issue by liujiqiangresearch** [facebookresearch/UnsupervisedMT#14]
While I am trying to train an NMT model, I got the following error message. What is important is that these error messages are generated after a period of successful training. I build PyTorch 0.4.0 from source on Centos running Python3.6. How to fix it?

THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
data_type: valid lang1: en lang2:fr
data_type: test lang1: en lang2:fr
Traceback (most recent call last):
  File "main.py", line 328, in <module>
    trainer.otf_bt(batch, params.lambda_xe_otfd, params.otf_backprop_temperature)
  File "/home/liujq/low-resourceMT/UnsupervisedMT/en2fr/baseline/NMT/src/trainer.py", line 706, in otf_bt
    loss.backward()
  File "/home/liujq/env_python3.6/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/liujq/env_python3.6/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

**Comment by glample** [comment]
What GPU do you use? It looks like you simply don't have enough memory. Can you have a look at https://github.com/facebookresearch/UnsupervisedMT/issues/13 and see if this helps?

**Comment by liujiqiangresearch** [comment]
My GPU is  GTX TITAN, whose memory is 11G. The NMT model executes with the parameters you provide. Thank you for your suggestion, and I will try it according to #13.

**Comment by glample** [comment]
Yeah the 11GB seems a bit much for the default configuration. Setting some of these values to `True`:
`share_encdec_emb` / `share_decpro_emb` / `share_output_emb`
Or setting `max_len` to 100 should be enough to run the model on your GPU, and should not have a significant impact on the performance.

Closing the issue for now, feel free to re-open if you still have the issue.

**Comment by liujiqiangresearch** [comment]
Thank you so much for your answer.
