### ISSUE TITLE
Why sort the two languages

### ISSUE THREAD

**Issue by shawnzaru** [facebookresearch/UnsupervisedMT#18]
In **check_all_data_params@src/data/loader.py** I saw the following lines
```
assert sorted(params.langs) == params.langs
...
assert lang1 < lang2 and lang1 in params.langs and lang2 in params.langs
```
I currently want to adapt the UnsupervisedMT to my own corpora which has .yy suffix as source language and .xx suffix as target language. However, the checks in here make it impossible to pass to the training phase. I am wondering why there is a need to sort the languages. If I deleted these checks will they affect the later training phase?

Thanks.

**Comment by glample** [comment]
I forgot if the ordering is critical, but I would recommend not removing the `assert` (the entire code was written under the assumption that languages were sorted). Can you provide the command you are using to run the code? I don't see why you couldn't feed the sorted languages as input (note that what is `lang1` and `lang2` is arbitrary, it has nothing to do with being source / target etc., so you should be fine with sorting them).
