### ISSUE TITLE
How to add para_dataset src and tgt into a single .pth file

### ISSUE THREAD

**Issue by arijitx** [facebookresearch/UnsupervisedMT#20]
Currently the process.py file gives a .pth file for a single text file so for src and tgt I will have two src.pth and tgt.pth, but when I need to pass the files to main.py it expects in the format 

`src-tgt:train12,val12,test12`

How to pass src and tgt .pth files separately ?

**Comment by Kelechukwu1** [comment]
Hi, what is the solution to this please?

**Comment by Kelechukwu1** [comment]
@arijitx
