### ISSUE TITLE
UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.

### ISSUE THREAD

**Issue by lbercken** [facebookresearch/UnsupervisedMT#21]
Hi, I'm trying to train your unsupervised NMT system (using my own data), but I'm getting these UserWarnings all the time:

``UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.``

I'm using pyTorch 0.4.1. I also tried it with 1.0 (by compiling from source, master branch), but the same thing happened. Is this a known issue?

Kind regards,
Laurens

**Comment by glample** [comment]
Hi,

Yes, `size_average` will be deprecated. But somehow the warning disappeared in PyTorch 0.5 for me (maybe they decided to keep it finally?) In any case, this is not a problem at all and you can ignore this warning for now.
