### ISSUE TITLE
The difference of vocabulary produced by fastText and  fast

### ISSUE THREAD

**Issue by liujiqiangresearch** [facebookresearch/UnsupervisedMT#26]
If the two languages do not share a vocabulary， the vocabulary could be generated by fastText, or also by the fastBPE.  I find that these two vocabulary is not the same, what is the difference?

**Comment by glample** [comment]
Sorry I can't understand your issue. What do you mean by generating vocabulary with fastText?

**Comment by liujiqiangresearch** [comment]
Yes, FastText and FastBPE chould both generate the vocabulary. But the vocabulary is somewhat different. I feel like I was mistaken, and the difference between vocabularies is that the order of words. Thank you very much.
