### ISSUE TITLE
About decoding

### ISSUE THREAD

**Issue by liujiqiangresearch** [facebookresearch/UnsupervisedMT#29]
Hi, I noticed that generating greedily in decoding time. Is there a big improvement in performance  if we use beam size in training time? Thank you.

**Comment by glample** [comment]
Hi,

Using beam to generate back-parallel data would hurt a little bit I think. See this: https://arxiv.org/abs/1808.09381

It would help at inference though. But in practice we don't do it (although we should..)

**Comment by liujiqiangresearch** [comment]
I will research this paper carefully and try it. Thank you for your help.
