### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by 15091444119** [facebookresearch/UnsupervisedMT#30]
my memory  usage is increased by 0.2M everytime when  decoding，does anyone have the same problem？ I mean memory but not cuda memory

**Comment by glample** [comment]
I don't think I noticed it. Is it a big issue? Do you observe out-of-memory errors because of this?

**Comment by glample** [comment]
I was not able to observe the issue. I'll close it for now as it does not seem critical (200MB of GPU memory would be more concerning). Feel free to re-open if this is blocking for you.
