### ISSUE TITLE
No module named torch

### ISSUE THREAD

**Issue by mohammedayub44** [facebookresearch/UnsupervisedMT#31]
Hi @glample 

I'm getting an error while replicating the steps. I did install pytorch in my conda environment. It gives error saying "No Module name torch" I see that's being imported in `/src/data/dictionary.py` . Not sure if I'm missing something. 

![image](https://user-images.githubusercontent.com/7122670/46693795-d8794200-cbd8-11e8-947c-01fb926351c2.png)

**Comment by glample** [comment]
Hi,

Yes, you didn't install PyTorch apparently. Have a look at http://pytorch.org/

**Comment by mohammedayub44** [comment]
@glample  my bad. the environment was messed up. Re-installed and it works. I started the get_data.sh script, eveything work fine but the FastText training is taking a huge time. I started this yesterday and it still show me 34 % done (pic as below). How do I accelerate this training.

![image](https://user-images.githubusercontent.com/7122670/46741293-b7652f80-cc72-11e8-8308-af239b9d339b.png)

**Comment by mohammedayub44** [comment]
Closing this,  opened another issue for the FastText part.  Thanks !
