### ISSUE TITLE
Running the model completely on CPU gives -1 BLEU

### ISSUE THREAD

**Issue by mohammedayub44** [facebookresearch/UnsupervisedMT#35]
Hi,

I'm trying to run the model training on CPU. 
**Changes Done:** 
I have removed all the references to cuda i.e. `.cuda()` mentions and also changed `torch.cuda` to just `torch` in the evaluator.py and trainer.py files .  
Changed `SIGUR1` to `SIGTERM` in mulitprocessing_event_loop.py because python multiprocessing in windows is different than in Linux.
I had to put torch.cuda.is_available() in `build_mt_model(params, data, torch.cuda.is_available())` in line 243 main.py since I was getting a CUDA error. 

With all the above changes done, I'm getting very different results when training, there seems to be an error calculating blue score as below.

![image](https://user-images.githubusercontent.com/7122670/46953657-713a1280-d05c-11e8-81a7-5743ddde0a73.png)

@glample 

Any help appreciated.

Thanks !

Mohammed Ayub

**Comment by glample** [comment]
Hi,

When you say you are getting very different results when training do you mean compared to when you run the code on GPU? Did you compare a CPU and GPU experiment? Can you provide the train.log as well? I'm not sure what is happening here, performance should be same on CPU and GPU so I'm curious to see the training losses.

**Comment by mohammedayub44** [comment]
@glample  I'm assuming GPU runs perfectly fine as no changes are required. Here is my train log for CPU run. It's only for couple of steps but it does gives the same error as before.
[train.log](https://github.com/facebookresearch/UnsupervisedMT/files/2480563/train.log)

**Comment by glample** [comment]
How do you know this is the correct output? For CPU it looks like you trained for 6 epochs and still get -1 BLEU. How much do you get if you train for 6 epochs on GPU?

**Comment by mohammedayub44** [comment]
Sorry I meant "meaningful output" like those INFO messages with different evaluation scores instead of WARNING messages. I don't get these warning messages "Impossible to parse BLEU score!" on the GPU.
Meantime - I'm running this on GPU for couple of epochs . I'll upload train.log when done. 

-Mohammed Ayub

**Comment by mohammedayub44** [comment]
@glample  
Here is the train.log for the run on GPU (not complete just 8 epochs). Blues scores show 0.0 , it doesn't give the warning message like the CPU run.  Is this expected ? 
[FAIR_train_GPU.log](https://github.com/facebookresearch/UnsupervisedMT/files/2484788/FAIR_train_GPU.log)

**Comment by glample** [comment]
Hey,
You are using `--epoch_size 500`, why? With this, the model only trains on a few batches per epoch. Default value for this is `--epoch_size 500000`.
Maybe you can try something in between `--epoch_size 100000` since CPU will be very slow, and check that you have the same performance at the end of one GPU and one CPU epoch.

**Comment by mohammedayub44** [comment]
@glample 500 , Just because I wanted to see if my CPU level changes to all files were correct and does it even start to run, which I'm guessing that all all changes were positive and the model runs fine. It just need to run more epochs to give good BLEU score.

**Comment by mohammedayub44** [comment]
Closing this for now. I will try running this for more epochs later, next month. If issues persists I will reopen. 
Thanks for you help @glample  appreciate it.
