### ISSUE TITLE
Inference again

### ISSUE THREAD

**Issue by shawnzaru** [facebookresearch/UnsupervisedMT#36]
Hi Glample,

Lately I have been trying to run the UnsupervisedMT in inference mode. Below is the command that at least work for me temporarily after many rounds of failed attempt.

```
python main.py \
  --exp_name mzpf \
  --exp_id infer \
  --reload_model './dumped/mzpf/infer/checkpoint.pth' \
  --eval_only 1 \
  --share_lang_emb True \
  --share_output_emb True \
  --langs 'en,fr' \
  --n_mono -1 \
  --reload_enc 1 \
  --reload_dec 1 \
  --reload_dis 0 \
  --mono_dataset 'en:./mzpf/mono/tok.unicode.shuffled.en.500.pth,,;fr:./mzpf/mono/tok.shuffled.fr.500.pth,,' \
  --para_dataset 'en-fr:,./mzpf/para/tok-para.shuffled.stripped.valid.XX.500.pth,./mzpf/para/infer.XX.500.pth' \
  --mono_directions 'en,fr' \
  --lambda_xe_mono '0:1,100000:0.1,300000:0'
```

In addition to some other parameters, it seems that the most important one is the `--para_dataset`, in which I have to trick the model by taking a parallel pair of inference set as test set. Currently I happen to have parallel data to run inference, but in case that I do not have parallel data, I am wondering how the inference mode is run? Or whether the above way of running inference as inspired by #15 is correct or not? Thanks.

**Comment by glample** [comment]
Hi,

Yes, the above way seems correct. If you don't have parallel data, you can simply run the same thing and use an arbitrary random text file with the same number of lines for the target file to create a fake parallel data.
Also, note that the checkpoint.pth is to restart the experiment, it contains a lot of things like training epoch, best scores, etc. In your case you want to reload a file like best-bleu_en_fr_valid.pth

**Comment by shawnzaru** [comment]
Also, I am trying to understand the difference between `checkpoint.pth` and `best-bleu_xxx.pth`. Do you mean `checkpoint.pth` is more redundant than `best-bleu_xxx.pth` or is it that in the inference case I have to reload `best-bleu_xxx.pth` instead of `checkpoint.pth`, because loading `checkpoint.pth` will make the program do things differently? Thanks.

**Comment by glample** [comment]
Because the target is just used to evaluate the BLEU score. But if you are just interested in inference, this is enough to do this. It's clearly not very efficient, but it's hacky workaround that should work until I add a `translate.py` file for inference.

Yes, `best-bleu_xxx.pth` only contains the model, this is what you need to use. `checkpoint.pth` contains the last model in the training experiment (not necessarily the best), along with the optimizer, the training parameters, etc.

**Comment by shawnzaru** [comment]
Thanks 👍
