### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Julisa-test** [facebookresearch/UnsupervisedMT#37]
When I run the unsupervised NMT codes, the following error is reported. My run command is as follows. Is there any parameter that is too large? 

`python main.py --exp_name mnzh --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb True --share_output_emb True --langs 'en,fr' --n_mono -1 --mono_dataset 'en:./data/mono/all.en.tok.60000.pth,,;fr:./data/mono/all.fr.tok.60000.pth,,' --para_dataset 'en-fr:,./data/para/dev/newstest2013-ref.XX.60000.pth,./data/para/dev/newstest2014-fren-src.XX.60000.pth' --mono_directions 'en,fr' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'fr-en-fr,en-fr-en' --pretrained_emb './data/mono/all.en-fr.60000.vec' --pretrained_out True --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 --otf_num_processes 8 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 500000 --stopping_criterion bleu_en_fr_valid,10`

![image](https://user-images.githubusercontent.com/38872215/47773283-871a2980-dd24-11e8-8c3f-7e222471d7dd.png)

GPU: GTX 1070
Python version: 3.6.2
Pytorch version: 0.4.1
CUDA Version 8.0.44

Look forward to your reply. Thanks!

**Comment by glample** [comment]
Hello,

Can you have a look at https://github.com/facebookresearch/UnsupervisedMT/issues/13 or https://github.com/facebookresearch/UnsupervisedMT/issues/14 ? If this doesn't solve your problem, please tell me.

**Comment by Julisa-test** [comment]
Thank you very much. It‘s finally work！And on newstest2014 en-fr, it give above 23.33 BLEU after 25 epochs. But there is another question. When I change my translation task to Mongolian-Chinese，I modified the /NMT/get_data.sh and got some data (/data/mono/all.mn.tok.6000.pth, /data/mono/all.zh.tok.6000.pth, /data/para/dev/val1w.XX.6000.pth, /data/para/dev/test1w.XX.6000.pth, /data/mono/all.mn-zh.6000.vec). 

![image](https://user-images.githubusercontent.com/38872215/48403273-85128a80-e768-11e8-9795-2106e27e0196.png)

Then I run the command as follows:
`python main.py --exp_name mn-zh --transformer True --n_enc_layers 3 --n_dec_layers 3 --share_enc 2 --share_dec 2 --max_len=100 --share_lang_emb True --share_output_emb True --langs 'mn,zh' --n_mono -1 --mono_dataset 'mn:./data/mono/all.mn.tok.6000.pth,,;zh:./data/mono/all.zh.tok.6000.pth,,' --para_dataset 'mn-zh:,./data/para/dev/val1w.XX.6000.pth,./data/para/dev/test1w.XX.6000.pth' --mono_directions 'mn,zh' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'zh-mn-zh,mn-zh-mn' --pretrained_emb './data/mono/all.mn-zh.6000.vec' --pretrained_out True --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 --otf_num_processes 8 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 20 --stopping_criterion bleu_mn_zh_valid,1`
![image](https://user-images.githubusercontent.com/38872215/48403938-0dddf600-e76a-11e8-86f0-8a63591a5cc3.png)

But the Bleu is 0, I want to know if NMT can be used for Mongolian-Chinese translation tasks. What should I do?

**Comment by glample** [comment]
You are only using 6000 BPE codes is that expected? Usually I use 60000. I tried 8000 once and it gave me pretty bad results too. Also, did you evaluate the word translation accuracy of your cross-lingual BPE embeddings? If you had a mn-zh dictionary you could evaluate the word translation accuracy using https://github.com/facebookresearch/MUSE or something.

Also, how big are your monolingual corpora? It looks like the training epoch finished in 8 seconds. You also set `--epoch_size 20`, why? Usually epoch size is around 100000 or something.

**Comment by Julisa-test** [comment]
Hi，I run the unsupervised NMT codes and PBSMT codes，but the BLEU are both 0.  Is there too little monolingual corpus?

NMT codes：
`python main.py --exp_name mn-zh --transformer True --n_enc_layers 2 --n_dec_layers 2 --share_enc 1 --share_dec 1 --max_len=50 --share_lang_emb True --share_encdec_emb True --share_decpro_emb True --share_output_emb True --langs 'mn,zh' --n_mono -1 --mono_dataset 'mn:./data/mono/all.mn.tok.40000.pth,,;zh:./data/mono/all.zh.tok.40000.pth,,' --para_dataset 'mn-zh:,./data/para/dev/val3k.XX.40000.pth,./data/para/dev/test3k.XX.40000.pth' --mono_directions 'mn,zh' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'zh-mn-zh,mn-zh-mn' --pretrained_emb './data/mono/all.mn-zh.40000.vec' --pretrained_out True --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 --otf_num_processes 8 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 100000 --stopping_criterion bleu_mn_zh_valid,10 --batch_size 32`
![image](https://user-images.githubusercontent.com/38872215/49276463-96260000-f4b9-11e8-988f-92250161b751.png)

PBSMT codes：
![image](https://user-images.githubusercontent.com/38872215/49276562-d6857e00-f4b9-11e8-8085-07bad69d53d3.png)

MUSE codes：
![image](https://user-images.githubusercontent.com/38872215/49276626-fddc4b00-f4b9-11e8-90b4-fb60c3a7aa7c.png)
