### ISSUE TITLE
Just use the language model without back translation

### ISSUE THREAD

**Issue by travel-go** [facebookresearch/UnsupervisedMT#39]
Hello, I just want to use  language model but don't use backTranslation, what should I do? I obversed two parameters: --otf_update_enc and --otf_update_dec.  Is there a parameter to set the step of Back Translation?

I am looking forward to replying to me.

**Comment by glample** [comment]
To disable back translation, you can set:
`--lambda_xe_otfd 0 --pivo_directions ''`

**Comment by travel-go** [comment]
Thank you for your reply.
