### ISSUE TITLE
binarize language model

### ISSUE THREAD

**Issue by lovecambi** [facebookresearch/UnsupervisedMT#4]
https://github.com/facebookresearch/UnsupervisedMT/blob/6b614e7c09ed2228311d85350b5031c779e41aff/PBSMT/run.sh#L236

Is it should be
```
$MOSES_PATH/bin/build_binary $SRC_LM_ARPA $SRC_LM_BLM
```
?

**Comment by glample** [comment]
You are right, thank you. Fixed in https://github.com/facebookresearch/UnsupervisedMT/commit/72ca4b1bd73b9208b2d0446b03ce8590a020f3c2
