### ISSUE TITLE
[Question] Did you use Discriminator for recent results

### ISSUE THREAD

**Issue by maxdel** [facebookresearch/UnsupervisedMT#40]
Hi,

It is clear that you used discriminator for the models in the paper `Unsupervised Machine Translation With Monolingual Data Only`.

But do you also use it to obtain results for NMT models presented in `Phrase-Based & Neural Unsupervised Machine Translation` paper? 

From the code it seems like if `--n_dis` parameter equals 0 (which is default), the discriminator is not used. You found it to have no positive effect?

Thanks!
Maksym

**Comment by glample** [comment]
Hi,

Indeed, in the last paper we didn't find any benefits using the discriminator. That being said, we didn't tune it very well, but I don't think it would make a big difference even if well tuned.
