### ISSUE TITLE
No language model pretraining in these results?

### ISSUE THREAD

**Issue by pranaymanocha** [facebookresearch/UnsupervisedMT#41]
Hi @glample ,
I was reading through the paper and the code and realized that though you mention (in the paper) that pretraining the language model is really important(otherwise the back-translation wouldn't work well), you don't explicitly pretrain the LM in the code(especially in the snippet where you mentioned the training command for NMT)- explicitly, the (--lm_before) flag is not set and by default it is 0(no LM pretrain). So the results which you report in the paper are with the LM or without? Because I would expect that pretrained LM would increase performance. If it achieves this performance, isn't a bit strange?

Thanks for your time.
Pranay

**Comment by pranaymanocha** [comment]
Hi, 
Thanks for the prompt response. I get the point that the denoising autoencoder acts like an LM. But shouldn't the denoising autoencoder be pre-trained first before being used in back-translation?

**Comment by glample** [comment]
You can do that. At the beginning, the back-translation is kind of useless because the generated translations are very bad. We tried to have a schedule to disable the back-translation initially, but this didn't make any difference on the final performance.

**Comment by pranaymanocha** [comment]
Thanks for the reply. Appreciate it.

**Comment by Julisa-test** [comment]
Hi @glample ,

My task is mn-zh translation，and when I run the task on unsupervised NMT, the result just is bleu_mn_zh_test -> 0.270000 and bleu_zh_mn_test -> 1.850000 after 20 epochs, I think maybe the Language model is not good, if I pre-trained the LM, how should I use it to the unsupervised NMT?

Thanks for your time.

**Comment by glample** [comment]
Hi,

I would recommend having a look at https://github.com/facebookresearch/XLM/ , XLM provides efficient framework for language model pretraining / unsupervised MT, and works much better than the code in this repo.

**Comment by Julisa-test** [comment]
Thanks for the reply. @glample
