### ISSUE TITLE
Curious- is there a way to not do BPE and do one hot encoding instead? 

### ISSUE THREAD

**Issue by pranaymanocha** [facebookresearch/UnsupervisedMT#43]
Hi,
I was working on BPE and wasn't really sure what was happening and so I wanted to try out doing one hot encoding (I know some words cannot be seen during train time but that's fine(aren't much for my dataset)) instead to see how to model performs. Is there a way I can plug in one hot encoding into this code?

Thanks,
Pranay

**Comment by glample** [comment]
I'm not sure I understand what you mean? BPE is about word segmentation, there is no relation between this and one-hot encoding.

**Comment by glample** [comment]
Closing for now. Feel free to re-open if needed.
