### ISSUE TITLE
which codes are related to the iterative back-translation of Algorithm 2 of PBSMT

### ISSUE THREAD

**Issue by qiang2100** [facebookresearch/UnsupervisedMT#45]
In algorithm 2 of PBSMT, it generates parallel pairs to optimize the model by iteration. But in the code of "PBSmT/run.sh", I cannot find the iteration process. Could you help me explain it? Thanks very much.

**Comment by qiang2100** [comment]
How to recover the Iterative back-translation of PBSMT in the original paper?

**Comment by glample** [comment]
Hi,

I didn't push our code for iterative back-translation, as it was deeply integrated into the Facebook infrastructure and it would not be very useful.
I didn't look at it carefully, but it looks like users implemented the iterative back-translation from this repo: https://github.com/sohuren/UnsupervisedMT/commits/master maybe it can be useful to you?

**Comment by qiang2100** [comment]
Thanks for your reply.
