### ISSUE TITLE
*help* I am confused about why this function just using the catche[0]?

### ISSUE THREAD

**Issue by zxqchat** [facebookresearch/UnsupervisedMT#53]
https://github.com/facebookresearch/UnsupervisedMT/blob/8ea252765ba81ed2cccb04336a63947159a790c8/NMT/src/trainer.py#L550-L570

Thank authors released the code . I am confused the function why this function just using the catche[0] to get results and not using other caches, whether it means the other is useless or not ?or other caches has been used in a unseen way? 

please help me figure out this, thanks a lot.

**Comment by myleott** [comment]
The cache is structured as a queue, where elements in the queue come from different workers. For example, if you had 3 workers then at initialization it might look like:
```
cache:
  0: first_result_generated_by_worker_0      <-- top of queue
  1: first_result_generated_by_worker_1
  2: first_result_generated_by_worker_2
  3: second_result_generated_by_worker_0
  4: second_result_generated_by_worker_1
  5: second_result_generated_by_worker_2
  (...)
```

Every time we consume a result from the cache, we remove it (`cache.pop(0)`) and enqueue another batch on the relevant worker. This keeps the cache a fixed size and ensures that all workers are busy.
