### ISSUE TITLE
Question About Discriminator

### ISSUE THREAD

**Issue by cocaer** [facebookresearch/UnsupervisedMT#54]
In trainer.py, I can not figure out [fake_y](https://github.com/facebookresearch/UnsupervisedMT/blob/5a4fff103eb3b0fd96b065238d49aa980a9807cd/NMT/src/trainer.py#L480).Why uses the fake target to train discriminator?

**Comment by glample** [comment]
Because the idea here is to fool the discriminator, by making the representations of English and French sentences closer together.

But although this is implemented, the discriminator is not something we used in our experiments.

**Comment by rajarsheem** [comment]
Why was it not used in the experiments? In the [paper](https://arxiv.org/pdf/1711.00043.pdf), the adversarial loss is claimed to be helping.
