### ISSUE TITLE
what does the "pretrained_out=True" mean?

### ISSUE THREAD

**Issue by ZhenYangIACAS** [facebookresearch/UnsupervisedMT#6]
I cannot figure out what do you mean by "pretrained_out=True". I didn't find how you use it. Do you mean the output projection matrix is also initialized from the pretrainied word embedding? Could you please show where you use it? Thank you. Actually, now my code on tensorflow is almost the same with yours. But I cannot get the comparable results with your code.

**Comment by glample** [comment]
Yes, your understanding is correct. This is happening here:
https://github.com/facebookresearch/UnsupervisedMT/blob/7b9ed95d1d39ba4ff97fd0a5795a098e15ad329b/NMT/src/model/pretrain_embeddings.py#L121-L122

If `pretrained_out` is `True`, we append the decoder projection layer to the list of embeddings to pretrain.

**Comment by ZhenYangIACAS** [comment]
So, do you think pre_trained projection layer makes great contribution to the translation performance? And do you think it is why  I cannot achieve comparable translation performance with yours?

**Comment by glample** [comment]
I remember I had significantly better results by pretraining the projection layer (forgot by how much though), but this could explain the difference.

**Comment by ZhenYangIACAS** [comment]
Ok, thank you. I will test it and wish success.
