### ISSUE TITLE
Question about EN-RU

### ISSUE THREAD

**Issue by cocaer** [facebookresearch/UnsupervisedMT#66]
Recently, I am doing some contrast work on EN-RU. I find the papaer does not mention the EN-RU data.So 
what's the training data? Is the [link](https://github.com/sohuren/UnsupervisedMT/blob/master/NMT_Improved/get_data_ru.sh) right? @glample

**Comment by glample** [comment]
Yes, this is the monolingual data we use (News Crawl, whenever it is available).
