### ISSUE TITLE
Mac can't go through line 149 in "get_data_*.sh".

### ISSUE THREAD

**Issue by Schureed** [facebookresearch/UnsupervisedMT#72]
Bash on macOS can't process with "-3", but is ok to with"21".

**Comment by derlin** [comment]
Here is how I solved it on Mac:

    # OUTPUT="${FILENAME::-3}" --> ERROR on MacOS:  substring expression < 0
    OUTPUT="${FILENAME::$((${#FILENAME} - 3))}" # same outcome, but working syntax
