### ISSUE TITLE
How long does NMT need to run

### ISSUE THREAD

**Issue by JxuHenry** [facebookresearch/UnsupervisedMT#73]

**Comment by glample** [comment]
Hi,

It takes about 1 or 2 day on 1 GPU. You can also check https://github.com/facebookresearch/XLM we have a more powerful implementation of the code in this repo. It can also run on multiple GPUs, and give a significantly better performance.

**Comment by JxuHenry** [comment]
> Hi,
> 
> It takes about 1 or 2 day on 1 GPU. You can also check https://github.com/facebookresearch/XLM we have a more powerful implementation of the code in this repo. It can also run on multiple GPUs, and give a significantly better performance.

Thans a lot

**Comment by sebastian-nehrdich** [comment]
Just a question regarding this: While XLM provides a much better performance, it is also much more computationally expensive, right? Are there any observations on how the two systems related to each other regarding training time?

**Comment by glample** [comment]
XLM is usually faster because it runs on multi-GPU. Multi-GPU allows to handle much larger batches, which is one of the reasons why it also works much better. If you run XLM on 1 GPU I guess the convergence time would be similar.
