### ISSUE TITLE
Train zh-en:assert sorted(params.langs) == params.langs

### ISSUE THREAD

**Issue by JxuHenry** [facebookresearch/UnsupervisedMT#78]
main.py --exp_name zhTest --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb True --share_output_emb True --langs 'zh,en' --n_mono -1 --mono_dataset 'zh:./data/mono/all.zh.tok.60000.pth,,;en:./data/mono/all.en.tok.60000.pth,,' --para_dataset 'zh-en:,./data/para/dev/newsdev2017-enzh-ref.XX.60000.pth,./data/para/dev/newsdev2017-zhen-src.XX.60000.pth' --mono_directions 'zh,en' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'en-zh-en,zh-en-zh' --pretrained_emb './data/mono/all.zh-en.60000.vec' --pretrained_out True --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 --otf_num_processes 30 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 500000 --stopping_criterion bleu_zh_en_valid,10

This my params

**Comment by glample** [comment]
Can you try `--langs 'en,zh'` instead of `'zh,en'` ?

**Comment by JxuHenry** [comment]
> Can you print lang1 and lang2 just before this assert fail? If you provided `--langs 'en,zh'` this issue should not appear.

**Sir, now I use the follwing params**
python main.py --exp_name zhTest --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb True --share_output_emb True --langs 'en,zh' --n_mono -1 --mono_dataset 'zh:./data/mono/all.zh.tok.60000.pth,,;en:./data/mono/all.en.tok.60000.pth,,' --para_dataset 'zh-en:,./data/para/newdev/newsdev2017-enzh-src.XX.60000.pth,./data/para/newdev/newsdev2017-zhen-ref.XX.60000.pth' --mono_directions 'zh,en' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'en-zh-en,zh-en-zh' --pretrained_emb './data/mono/all.zh-en.60000.vec' --pretrained_out True --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 --otf_num_processes 30 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 500000 --stopping_criterion bleu_zh_en_valid,10
**it still give the same error, and the following were what I print**
lang1: zh
lang2: en
Traceback (most recent call last):
  File "main.py", line 359, in <module>
    main(params)
  File "main.py", line 237, in main
    check_all_data_params(params)
  File "/data/xj/UNMT/UnsupervisedMT-master/NMT/src/data/loader.py", line 340, in check_all_data_params
    assert lang1 < lang2 and lang1 in params.langs and lang2 in params.langs
AssertionError

**Comment by glample** [comment]
Try to replace 'zh-en' by 'en-zh' at the beginning of --para_dataset

**Comment by JxuHenry** [comment]
> Try to replace 'zh-en' by 'en-zh' at the beginning of --para_dataset

**OK，sir,and then it get the followinig error**
INFO - 04/10/19 19:37:51 - 0:00:00 - ============ Monolingual data (zh)
INFO - 04/10/19 19:37:51 - 0:00:00 - Loading data from ./data/mono/all.zh.tok.60000.pth ...
INFO - 04/10/19 19:37:52 - 0:00:01 - 249647978 words (71967 unique) in 10000000 sentences. 0 unknown words (0 unique).
============================
lang:zh
data['dico']:{'en': <src.data.dictionary.Dictionary object at 0x7fdd20be1b38>, 'zh': <src.data.dictionary.Dictionary object at 0x7fdd20be1f28>}
============================
Traceback (most recent call last):
  File "main.py", line 359, in <module>
    main(params)
  File "main.py", line 242, in main
    data = load_data(params)
  File "/data/xj/UNMT/UnsupervisedMT-master/NMT/src/data/loader.py", line 506, in load_data
    load_mono_data(params, data)
  File "/data/xj/UNMT/UnsupervisedMT-master/NMT/src/data/loader.py", line 289, in load_mono_data
    assert data['dico'][lang] == mono_data['dico']
AssertionError
and ,all the '.pth' file generated by the 'preprocess.py'

**Comment by JxuHenry** [comment]
> Try to replace 'zh-en' by 'en-zh' at the beginning of --para_dataset

**OK，sir,and then it get the followinig error**
INFO - 04/10/19 19:37:51 - 0:00:00 - ============ Monolingual data (zh)
INFO - 04/10/19 19:37:51 - 0:00:00 - Loading data from ./data/mono/all.zh.tok.60000.pth ...
INFO - 04/10/19 19:37:52 - 0:00:01 - 249647978 words (71967 unique) in 10000000 sentences. 0 unknown words (0 unique).
lang:zh
data['dico']:{'en': <src.data.dictionary.Dictionary object at 0x7fdd20be1b38>, 'zh': <src.data.dictionary.Dictionary object at 0x7fdd20be1f28>}
Traceback (most recent call last):
File "main.py", line 359, in 
main(params)
File "main.py", line 242, in main
data = load_data(params)
File "/data/xj/UNMT/UnsupervisedMT-master/NMT/src/data/loader.py", line 506, in load_data
load_mono_data(params, data)
File "/data/xj/UNMT/UnsupervisedMT-master/NMT/src/data/loader.py", line 289, in load_mono_data
assert data['dico'][lang] == mono_data['dico']
AssertionError
**and ,all the '.pth' file generated by the 'preprocess.py'**

**Comment by glample** [comment]
It seems the datasets have been preprocessed with different vocabularies, as the dictionaries are not the sames across binary files. Can you check you preprocessed the binary files with the same vocabulary?

**Comment by JxuHenry** [comment]
> It seems the datasets have been preprocessed with different vocabularies, as the dictionaries are not the sames across binary files. Can you check you preprocessed the binary files with the same vocabulary?

**Sir, I modified the file 'get_data_enfr.sh' which you provided to processing my data. I used each step of this file to processing my data.**

**Comment by JxuHenry** [comment]
> > It seems the datasets have been preprocessed with different vocabularies, as the dictionaries are not the sames across binary files. Can you check you preprocessed the binary files with the same vocabulary?
> 
> **Sir, I modified the file 'get_data_enfr.sh' which you provided to processing my data. I used each step of this file to processing my data.**

**Sir, I used the modified file to re-process the data and the same error occurred again. Do you need to look at the file I wrote, I will send it to you by your email in your published paper.**

**Comment by JxuHenry** [comment]
> > > It seems the datasets have been preprocessed with different vocabularies, as the dictionaries are not the sames across binary files. Can you check you preprocessed the binary files with the same vocabulary?
> > 
> > 
> > **Sir, I modified the file 'get_data_enfr.sh' which you provided to processing my data. I used each step of this file to processing my data.**
> 
> **Sir, I used the modified file to re-process the data and the same error occurred again. Do you need to look at the file I wrote, I will send it to you by your email in your published paper.**
And sir, How to check my binary files?

**Comment by JxuHenry** [comment]
> It seems the datasets have been preprocessed with different vocabularies, as the dictionaries are not the sames across binary files. Can you check you preprocessed the binary files with the same vocabulary?

**OK，I see. Thank you sir, and I have a question, the following log is that means I training a en-zh or zh-en?**
INFO - 04/12/19 08:06:56 - 0:00:51 - Parallel data      - valid -   en ->   zh:      2002
INFO - 04/12/19 08:06:56 - 0:00:51 - Parallel data      -  test -   en ->   zh:      2002
INFO - 04/12/19 08:06:56 - 0:00:51 - Monolingual data   - train -           zh:   9989887
INFO - 04/12/19 08:06:56 - 0:00:51 - Monolingual data   - valid -           zh:         0
INFO - 04/12/19 08:06:56 - 0:00:51 - Monolingual data   -  test -           zh:         0
INFO - 04/12/19 08:06:56 - 0:00:51 - Monolingual data   - train -           en:   9995348
INFO - 04/12/19 08:06:56 - 0:00:51 - Monolingual data   - valid -           en:         0
INFO - 04/12/19 08:06:56 - 0:00:51 - Monolingual data   -  test -           en:         0
