### ISSUE TITLE
How long would it take for you to train fastText?

### ISSUE THREAD

**Issue by Schureed** [facebookresearch/UnsupervisedMT#81]
I have to run fastText for days to get a .vec file. Is it a regular situation?

**Comment by glample** [comment]
Yes or you can download pretrained fastText embeddings on the fastText website. It's probably better to retrain them though, so that you match exactly the domain of your training set, and that the vocabulary is identical.

**Comment by Schureed** [comment]
> Yes or you can download pretrained fastText embeddings on the fastText website. It's probably better to retrain them though, so that you match exactly the domain of your training set, and that the vocabulary is identical.

Thank you very much :)
