### ISSUE TITLE
Train NMT with my own dataset

### ISSUE THREAD

**Issue by jackson1895** [facebookresearch/UnsupervisedMT#86]
Hello, can I train my own machine translation task through NMT, and if so, what conditions do the dataset format need to meet?

**Comment by zhang-jinyi** [comment]
Please revise the [https://github.com/facebookresearch/UnsupervisedMT/blob/master/NMT/get_data_enfr.sh](https://github.com/facebookresearch/UnsupervisedMT/blob/master/NMT/get_data_enfr.sh) with your own train-data and valid-data, test-data. It's easy for you.
