### ISSUE TITLE
Broken pipe from multiprocessing 

### ISSUE THREAD

**Issue by thammegowda** [facebookresearch/UnsupervisedMT#87]
running transformer NMT on de-en dataset.
I got the  dataset prepared by the `get_data_deen.sh` script 

and the `para_dataset` paths specified in the below command are valid
```bash
 python main.py --exp_name nmt-deen-tfm --transformer True \
 --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3\
 --share_lang_emb True --share_output_emb True --langs 'de,en' \
 --n_mono -1 --mono_dataset 'en:./data/mono/all.en.tok.60000.pth,,;de:./data/mono/all.de.tok.60000.pth,,' \
--para_dataset 'de-en:,./data/para/dev/newstest2015-deen.XX.60000.pth,./data/para/dev/newstest2016-deen.XX.60000.pth'  \
--mono_directions 'de,en' --word_shuffle 3 --word_dropout 0.1 \
--word_blank 0.2 --pivo_directions 'de-en-de,en-de-en' \
--pretrained_emb './data/mono/all.en-de.60000.vec' --pretrained_out True \
 --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 \
--otf_num_processes 32 --otf_sync_params_every 1000 \
 --enc_optimizer adam,lr=0.0001 --epoch_size 500000 \
--stopping_criterion bleu_de_en_valid,10
```
However, the job fails with `Broken pipe ` error. 
```
INFO - 06/06/19 12:05:16 - 0:00:34 - Discriminator: None
INFO - 06/06/19 12:05:16 - 0:00:34 - LM: None

INFO - 06/06/19 12:05:18 - 0:00:36 - Starting subprocesses for OTF generation ...
INFO - 06/06/19 12:05:18 - 0:00:36 - Stopping criterion: bleu_de_en_valid,10
INFO - 06/06/19 12:05:18 - 0:00:36 - Test: Parameters are shared correctly.
INFO - 06/06/19 12:05:20 - 0:00:38 - ====================== Starting epoch 0 ... ======================
INFO - 06/06/19 12:05:20 - 0:00:38 - Creating new training encdec,de iterator ...

/nas/home/tg/libs/miniconda3/envs/fb-unsupmt/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwis
e_mean' instead.
  warnings.warn(warning.format(ret))
 ... some more of those warnings ...

INFO - 06/06/19 12:05:30 - 0:00:48 - Creating new training encdec,en iterator ...
INFO - 06/06/19 12:05:45 - 0:01:03 - Populating initial OTF generation cache ...
INFO - 06/06/19 12:05:45 - 0:01:03 - Creating new training otf,de iterator ...
INFO - 06/06/19 12:05:48 - 0:01:06 - Creating new training otf,en iterator ...
Traceback (most recent call last):
  File "main.py", line 356, in <module>
    main(params)
  File "main.py", line 317, in main
    batches = next(otf_iterator)
  File "UnsupervisedMT/NMT/src/trainer.py", line 558, in otf_bt_gen_async
    for i in range(init_cache_size)
  File "UnsupervisedMT/NMT/src/trainer.py", line 558, in <listcomp>
    for i in range(init_cache_size)
  File "UnsupervisedMT/NMT/src/multiprocessing_event_loop.py", line 82, in call_async
    self.input_pipes[rank].send((result_type, action, kwargs))
  File "/nas/home/tg/libs/miniconda3/envs/fb-unsupmt/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/nas/home/tg/libs/miniconda3/envs/fb-unsupmt/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/nas/home/tg/libs/miniconda3/envs/fb-unsupmt/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```
I am clueless about why the connection/pipe breaks. 

Environment: 
python 3.6, cuda 9, torch 0.4.1 on Centos 7.4

@glample Any small hint on how to pass through this error would be greatly appreciated. Thanks

**Comment by glample** [comment]
Hi,

It seems some issue is happening on the CPU threads in charge of generating the back-parallel data, and that the error is not printed in the main thread. We had this issue in the past and were never able to fix it... I would recommend using https://github.com/facebookresearch/XLM, this is an updated version of this repository, which provides much better results, and is much faster (it also supports distributed float16 training). The data format is the same for the XLM library, so you probably just need to download it and run it directly without re-binarizing the dataset.

**Comment by thammegowda** [comment]
Great! Thank you very much, I will switch to XLM :)

**Comment by masonreznov** [comment]
> running transformer NMT on de-en dataset.
> I got the dataset prepared by the `get_data_deen.sh` script
> 
> and the `para_dataset` paths specified in the below command are valid
> 
> ```shell
>  python main.py --exp_name nmt-deen-tfm --transformer True \
>  --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3\
>  --share_lang_emb True --share_output_emb True --langs 'de,en' \
>  --n_mono -1 --mono_dataset 'en:./data/mono/all.en.tok.60000.pth,,;de:./data/mono/all.de.tok.60000.pth,,' \
> --para_dataset 'de-en:,./data/para/dev/newstest2015-deen.XX.60000.pth,./data/para/dev/newstest2016-deen.XX.60000.pth'  \
> --mono_directions 'de,en' --word_shuffle 3 --word_dropout 0.1 \
> --word_blank 0.2 --pivo_directions 'de-en-de,en-de-en' \
> --pretrained_emb './data/mono/all.en-de.60000.vec' --pretrained_out True \
>  --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 \
> --otf_num_processes 32 --otf_sync_params_every 1000 \
>  --enc_optimizer adam,lr=0.0001 --epoch_size 500000 \
> --stopping_criterion bleu_de_en_valid,10
> ```
> 
> However, the job fails with `Broken pipe ` error.
> 
> ```
> INFO - 06/06/19 12:05:16 - 0:00:34 - Discriminator: None
> INFO - 06/06/19 12:05:16 - 0:00:34 - LM: None
> 
> INFO - 06/06/19 12:05:18 - 0:00:36 - Starting subprocesses for OTF generation ...
> INFO - 06/06/19 12:05:18 - 0:00:36 - Stopping criterion: bleu_de_en_valid,10
> INFO - 06/06/19 12:05:18 - 0:00:36 - Test: Parameters are shared correctly.
> INFO - 06/06/19 12:05:20 - 0:00:38 - ====================== Starting epoch 0 ... ======================
> INFO - 06/06/19 12:05:20 - 0:00:38 - Creating new training encdec,de iterator ...
> 
> /nas/home/tg/libs/miniconda3/envs/fb-unsupmt/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwis
> e_mean' instead.
>   warnings.warn(warning.format(ret))
>  ... some more of those warnings ...
> 
> INFO - 06/06/19 12:05:30 - 0:00:48 - Creating new training encdec,en iterator ...
> INFO - 06/06/19 12:05:45 - 0:01:03 - Populating initial OTF generation cache ...
> INFO - 06/06/19 12:05:45 - 0:01:03 - Creating new training otf,de iterator ...
> INFO - 06/06/19 12:05:48 - 0:01:06 - Creating new training otf,en iterator ...
> Traceback (most recent call last):
>   File "main.py", line 356, in <module>
>     main(params)
>   File "main.py", line 317, in main
>     batches = next(otf_iterator)
>   File "UnsupervisedMT/NMT/src/trainer.py", line 558, in otf_bt_gen_async
>     for i in range(init_cache_size)
>   File "UnsupervisedMT/NMT/src/trainer.py", line 558, in <listcomp>
>     for i in range(init_cache_size)
>   File "UnsupervisedMT/NMT/src/multiprocessing_event_loop.py", line 82, in call_async
>     self.input_pipes[rank].send((result_type, action, kwargs))
>   File "/nas/home/tg/libs/miniconda3/envs/fb-unsupmt/lib/python3.6/multiprocessing/connection.py", line 206, in send
>     self._send_bytes(_ForkingPickler.dumps(obj))
>   File "/nas/home/tg/libs/miniconda3/envs/fb-unsupmt/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
>     self._send(header + buf)
>   File "/nas/home/tg/libs/miniconda3/envs/fb-unsupmt/lib/python3.6/multiprocessing/connection.py", line 368, in _send
>     n = write(self._handle, buf)
> BrokenPipeError: [Errno 32] Broken pipe
> ```
> 
> I am clueless about why the connection/pipe breaks.
> 
> Environment:
> python 3.6, cuda 9, torch 0.4.1 on Centos 7.4
> 
> @glample Any small hint on how to pass through this error would be greatly appreciated. Thanks

I ran into the same problem. I think it is with this line
 `--otf_num_processes 32`
Check your cpu cores/threads, and minimise the value if you have lower number of threads available in the cpu.
