### ISSUE TITLE
Error in runny bash command. 

### ISSUE THREAD

**Issue by ykkhan** [facebookresearch/UnsupervisedMT#99]
When I run **./get_data_enfr.sh**

![Screenshot from 2020-08-27 21-44-05](https://user-images.githubusercontent.com/42977303/91472155-8024b980-e8b0-11ea-80f4-e5aff59ea462.png)
![IMG_20200827_214458](https://user-images.githubusercontent.com/42977303/91471744-e6f5a300-e8af-11ea-8206-bb4146a7f920.jpg)

And my PC got stuck at this stage. I tried it multiple time. 
Is there any thing wrong.
why it is showing empty sentences etc.

**Comment by glample** [comment]
The empty sentences are fine, this is just a warning. You can simply ignore it.

**Comment by ykkhan** [comment]
Ok, thanks for reply. 
Why my PC got stuck at 800000 sentences. ?
